language: python

python:
- 3.8

before_install:
- travis_retry curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py > /tmp/get-poetry.py
- travis_retry python /tmp/get-poetry.py --preview --yes
- source $HOME/.poetry/env

install:
- travis_retry poetry install

script:
- poetry run pytest --cov --cov-report=xml

after_success:
# Upload coverage report to codecov.io
- bash <(curl -s https://codecov.io/bash)
# Bump version to x.x.BUILD_NUMBER
- sed -i "s/\(version = \"[[:digit:]]\.[[:digit:]]\).*\"/\1.$TRAVIS_BUILD_NUMBER\"/" pyproject.toml
# Publish package
- travis_retry poetry publish --build --username "$PYPI_USERNAME" --password "$PYPI_PASSWORD"
